# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Horisyre/my-flyrank-ml-intern-starter-project/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

In [2]:

import pandas as pd
import os, sys, subprocess

IN_COLAB = "google.colab" in sys.modules
REPO_URL = "https://github.com/flyrank-bih/flyrank-ml-internship-starter"
REPO_DIR = "flyrank-ml-internship-starter"

if IN_COLAB:
    if not os.path.isdir(REPO_DIR):
        subprocess.run(["git", "clone", "--depth", "1", REPO_URL, REPO_DIR], check=True)
    os.chdir(REPO_DIR)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"], check=True)
else:
    # find the repo root from wherever this kernel started
    while not os.path.isdir("data/raw") and os.getcwd() != "/":
        os.chdir("..")

df = pd.read_csv("data/raw/ranking_lifecycle.csv",low_memory=False)
print(df.head(1))


            client_hash_id           content_hash_id  \
0  client_62f4a7e64f5e0096  content_ec0856ccefd6c85f   

            keyword_hash_id  keyword_char_count  keyword_token_count  \
0  keyword_4f32fa497f4cc9e3                  52                    9   

     public_url_hash_id  public_url_char_count public_url_path_depth  \
0  url_a3bd5da6c50a8fd4                    101                     3   

    content_title_hash_id  content_title_char_count  ...  ai_sessions_30d  \
0  title_229e09c84b7c8e80                        52  ...               \N   

  scroll_events_30d ctr_30d avg_position_30d engagement_rate_30d  \
0                \N     0.0             13.0                  \N   

   scroll_rate_30d  ai_traffic_pct_30d  impression_tier  position_tier  \
0               \N                  \N              low       striking   

   health_score  
0            20  

[1 rows x 34 columns]


## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [ ]:
data = {
    "Bucket": ["Feature", "Feature", "Feature", "Label", "Context", "Excluded"],
    "Field": [
        "health_score",
        "ctr_30d",
        "clicks_30d",
        "impression_tier",
        "content_id",
        "All other candidate features not listed as a feature in this table"
    ],
    "Reason": [
        "Used as a model input, due to high ",
        "Used as a model input",
        "Used as a model input",
        "What the model predicts",
        "Identifies the content",
        "Temporarily excluded from the baseline, due to low correlation with the label, but may be included in future iterations of the model"
    ]
}




## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [ ]:

import pandas as pd
import os, sys, subprocess

IN_COLAB = "google.colab" in sys.modules
REPO_URL = "https://github.com/flyrank-bih/flyrank-ml-internship-starter"
REPO_DIR = "flyrank-ml-internship-starter"

if IN_COLAB:
    if not os.path.isdir(REPO_DIR):
        subprocess.run(["git", "clone", "--depth", "1", REPO_URL, REPO_DIR], check=True)
    os.chdir(REPO_DIR)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"], check=True)
else:
    # find the repo root from wherever this kernel started
    while not os.path.isdir("data/raw") and os.getcwd() != "/":
        os.chdir("..")

df = pd.read_csv("data/raw/ranking_lifecycle.csv",low_memory=False)



#1 row = 1 content item + 1 client
print(df.head(1))

#Time window and number of rows: The dataset contains content records spanning from November 2024 to June 2026 and has 205749 rows
print(df.shape[0])
print(df['content_created_at'].min(), df['content_created_at'].max())

# data available stays the same when filtered  by client_has_gsc stays the same but when filtered by client_has_ga4 it drops 
# to 152162 rows.
print(df[df['client_has_ga4'] == True].shape[0])
print(df[df['client_has_gsc'] == False].shape[0])

# Verifying features
#feature frame
X = ["health_score",
      "ctr_30d",
      "clicks_30d",]

# Data contains no missing values for all intial feature inputs, which is important for model training and evaluation.
print(df[X].isnull().sum()) 



            client_hash_id           content_hash_id  \
0  client_62f4a7e64f5e0096  content_ec0856ccefd6c85f   

            keyword_hash_id  keyword_char_count  keyword_token_count  \
0  keyword_4f32fa497f4cc9e3                  52                    9   

     public_url_hash_id  public_url_char_count public_url_path_depth  \
0  url_a3bd5da6c50a8fd4                    101                     3   

    content_title_hash_id  content_title_char_count  ...  ai_sessions_30d  \
0  title_229e09c84b7c8e80                        52  ...               \N   

  scroll_events_30d ctr_30d avg_position_30d engagement_rate_30d  \
0                \N     0.0             13.0                  \N   

   scroll_rate_30d  ai_traffic_pct_30d  impression_tier  position_tier  \
0               \N                  \N              low       striking   

   health_score  
0            20  

[1 rows x 34 columns]
205749
{"value":"2024-11-22T14:48:37.000Z"} {"value":"2026-06-19T00:11:21.342378000Z"}
152162
0
h

## 1. Grain

One row represents one content item associated with one client.

## 2. Time window and dataset size

The dataset contains content records spanning from November 2024 to June 2026 and contains 205,749 rows.

## 3. Data availability

GSC is available across the dataset, while filtering for GA4 availability reduces the dataset to 152,162 rows. This indicates that GA4 data is not available for all content records, while GSC is available across the dataset.

## 4. Initial features

The initial feature frame consists of three model inputs: `health_score`, `ctr_30d`, and `clicks_30d`. These features will be used as the initial inputs for the classification model.

## 5. Missing values

The three initial model inputs contain no missing values. This means missingness does not currently prevent these features from being used for model training and evaluation.

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*


In [4]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import pandas as pd
import os, sys, subprocess
import json

IN_COLAB = "google.colab" in sys.modules
REPO_URL = "https://github.com/flyrank-bih/flyrank-ml-internship-starter"
REPO_DIR = "flyrank-ml-internship-starter"

if IN_COLAB:
    if not os.path.isdir(REPO_DIR):
        subprocess.run(["git", "clone", "--depth", "1", REPO_URL, REPO_DIR], check=True)
    os.chdir(REPO_DIR)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"], check=True)
else:
    # find the repo root from wherever this kernel started
    while not os.path.isdir("data/raw") and os.getcwd() != "/":
        os.chdir("..")

df = pd.read_csv("data/raw/ranking_lifecycle.csv",low_memory=False)
df["content_date"] = df["content_created_at"].apply(
    lambda x: json.loads(x)["value"]
)

df["content_date"] = pd.to_datetime(df["content_date"], utc=True)
df["month"] = df["content_date"].dt.to_period("M")
print(df["month"].value_counts().sort_index())
# We can see that the data is not evenly distributed across months, with some months having significantly more rows than others. 
# This could potentially affect the model's performance if certain months are overrepresented in the training data.

print(df.isnull().sum())
# We see that there are no missing values in the features, which is good for model training. 

print(df[["client_has_gsc", "client_has_ga4"]].value_counts())
# Here we see all content rows have GSC enabled, but only some have GA4 enabled. 
# This could potentially affect the model's performance if certain clients are overrepresented in the training data.

print(df.columns)
# Lack of daily observations: Performance metrics are provided as 30-day
# aggregates rather than daily observations. Therefore, the dataset cannot
# capture day-to-day variation or identify precisely when performance changes
# occurred within the measurement window. This also provides limited evidence
# for explaining why performance metrics changed.


C:\Users\horis\AppData\Local\Temp\ipykernel_7556\460022859.py:27: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["month"] = df["content_date"].dt.to_period("M")


month
2024-11      606
2024-12     1398
2025-01     2770
2025-02     6183
2025-03     8469
2025-04     4494
2025-05     3697
2025-06     4489
2025-07    20187
2025-08    14778
2025-09    11270
2025-10     9326
2025-11     3163
2025-12    11412
2026-01    18291
2026-02    20172
2026-03    20053
2026-04    23086
2026-05    17209
2026-06     4696
Freq: M, Name: count, dtype: int64
client_hash_id               0
content_hash_id              0
keyword_hash_id              0
keyword_char_count           0
keyword_token_count          0
public_url_hash_id           0
public_url_char_count        0
public_url_path_depth        0
content_title_hash_id        0
content_title_char_count     0
content_title_token_count    0
search_volume                0
content_type                 0
main_intent                  0
content_created_at           0
content_age_days             0
client_has_gsc               0
client_has_ga4               0
impressions_30d              0
clicks_30d                   0

## 4. Data limits

### Unbalanced history

The dataset is not evenly distributed across months, with some months containing substantially more observations than others. This may affect model generalization if certain periods are overrepresented during training.

### Missing values

The dataset is checked for missing values to determine whether missing data could limit the use of the available variables for modelling.

### Uneven GSC and GA4 availability

GSC and GA4 availability is not necessarily consistent across all content records. Differences in availability may limit comparability between observations when Analytics-based variables are considered.

### Lack of daily observations

The dataset contains performance metrics aggregated over 30-day periods rather than daily performance observations. Therefore, it cannot capture day-to-day variation or identify precisely when performance changes occurred within a measurement window. This limits the ability to determine why performance changed based on daily or shorter-term behaviour.

### Available data fields

The available columns are inspected to identify the level of detail and types of variables present in the dataset. This helps determine what information is available for modelling and what information is absent from the dataset.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.